name: filling_slider
description: Flutter package that allows you to create a IOS design sider component.
version: 0.0.2
homepage: https://github.com/IvanSupervan/filling_slider

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: